source 'https://rubygems.org'

gem 'rails', '2.3.18'

gem "nifty-generators"
gem 'haml', "3.1.8"


group :development, :test do
  gem 'sqlite3'
  gem 'rspec'
  gem 'guard-rspec'
  gem 'guard-spork'
  gem 'childprocess'
  gem 'spork'
end

group :test do
  gem "capybara", "1.1.1"
  gem "cucumber", "1.1.0"
  gem "cucumber-rails", "0.3.2"
  gem 'factory_girl'
  gem 'database_cleaner'
end